graph_functions:
  - name: gs.function.abs
    description: ""
    params:
      - name: value
        type:
          primitive_type: DT_SIGNED_INT32
    returns:
      - name: abs_value
        type:
          primitive_type: DT_SIGNED_INT32
  - name: gs.function.datetime
    description: ""
    params:
      - name: value
        type:
          primitive_type: DT_SIGNED_INT32
    returns:
      - name: timestamp
        type:
          temporal:
            timestamp:
  - name: gs.function.get
    description: ""
    params:
      - name: array
        type:
          primitive_type: DT_ANY
      - name: index
        type:
          primitive_type: DT_SIGNED_INT32
    returns:
      - name: value
        type:
          primitive_type: DT_SIGNED_INT64
  - name: gs.function.toFloat
    description: ""
    params:
      - name: integer
        type:
          primitive_type: DT_SIGNED_INT32
    returns:
      - name: float
        type:
          primitive_type: DT_FLOAT