queries:
  - name: "insert_comment"
    description: "insert_comment"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_comment_hasCreator_person"
    description: "insert_comment_hasCreator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment_hasCreator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_comment_hasTag_tag"
    description: "insert_comment_hasTag_tag"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment_hasTag_tag.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_comment_isLocatedIn_country"
    description: "insert_comment_isLocatedIn_country"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment_isLocatedIn_country.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_comment_replyOf_comment"
    description: "insert_comment_replyOf_comment"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment_replyOf_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_comment_replyOf_post"
    description: "insert_comment_replyOf_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_comment_replyOf_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_forum"
    description: "insert_forum"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_forum.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_forum_containerOf_post"
    description: "insert_forum_containerOf_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_forum_containerOf_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_forum_hasMember_person"
    description: "insert_forum_hasMember_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_forum_hasMember_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_forum_hasModerator_person"
    description: "insert_forum_hasModerator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_forum_hasModerator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_forum_hasTag_tag"
    description: "insert_forum_hasTag_tag"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_forum_hasTag_tag.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person"
    description: "insert_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_hasInterest_tag"
    description: "insert_person_hasInterest_tag"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_hasInterest_tag.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_isLocatedIn_city"
    description: "insert_person_isLocatedIn_city"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_isLocatedIn_city.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_knows_person"
    description: "insert_person_knows_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_knows_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_likes_comment"
    description: "insert_person_likes_comment"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_likes_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_likes_post"
    description: "insert_person_likes_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_likes_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_studyAt_university"
    description: "insert_person_studyAt_university"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_studyAt_university.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_person_workAt_company"
    description: "insert_person_workAt_company"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_person_workAt_company.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_post"
    description: "insert_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_post_hasCreator_person"
    description: "insert_post_hasCreator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_post_hasCreator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_post_hasTag_tag"
    description: "insert_post_hasTag_tag"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_post_hasTag_tag.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "insert_post_isLocatedIn_country"
    description: "insert_post_isLocatedIn_country"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libinsert_post_isLocatedIn_country.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_comment"
    description: "delete_comment"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libdelete_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_forum"
    description: "delete_forum"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libdelete_forum.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_message"
    description: "delete_person_message"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libdelete_person_message.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_forum"
    description: "delete_person_forum"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libdelete_person_forum.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_post"
    description: "delete_post"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libdelete_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_comment_hasCreator_person"
    description: "delete_comment_hasCreator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_comment_hasCreator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_comment_isLocatedIn_country"
    description: "delete_comment_isLocatedIn_country"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_comment_isLocatedIn_country.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_comment_replyOf_comment"
    description: "delete_comment_replyOf_comment"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_comment_replyOf_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_comment_replyOf_post"
    description: "delete_comment_replyOf_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_comment_replyOf_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_forum_containerOf_post"
    description: "delete_forum_containerOf_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_forum_containerOf_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_forum_hasMember_person"
    description: "delete_forum_hasMember_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_forum_hasMember_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_forum_hasModerator_person"
    description: "delete_forum_hasModerator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_forum_hasModerator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_isLocatedIn_city"
    description: "delete_person_isLocatedIn_city"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_person_isLocatedIn_city.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_knows_person"
    description: "delete_person_knows_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_person_knows_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_likes_comment"
    description: "delete_person_likes_comment"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_person_likes_comment.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_person_likes_post"
    description: "delete_person_likes_post"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_person_likes_post.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_post_hasCreator_person"
    description: "delete_post_hasCreator_person"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_post_hasCreator_person.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_post_isLocatedIn_country"
    description: "delete_post_isLocatedIn_country"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_post_isLocatedIn_country.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "delete_post_isLocatedIn_country"
    description: "delete_post_isLocatedIn_country"
    mode: "WRITE"
    extension: ".so"
    library: "/path/libdelete_post_isLocatedIn_country.so"
    params:
      - name: "csv_path"
        type: "string"
  - name: "bi4_precompute"
    description: "bi4_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libbi4_precompute.so"
  - name: "bi6_precompute"
    description: "bi6_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libbi6_precompute.so"
  - name: "interaction1_count_precompute"
    description: "interaction1_count_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libinteraction1_count_precompute.so"
  - name: "interaction2_count_precompute"
    description: "interaction2_count_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libinteraction2_count_precompute.so"
  - name: "bi20_precompute"
    description: "bi20_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libbi20_precompute.so"
  - name: "comment_root_precompute"
    description: "interaction1_count_precompute"
    mode: "READ_WRITE"
    extension: ".so"
    library: "/path/libcomment_root_precompute.so"
  - name: "bi1"
    description: "bi1"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi1.so"
    params:
      - name: "datetime"
        type: "timestamp"
  - name: "bi2"
    description: "bi2"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi2.so"
    params:
      - name: "tagClass"
        type: "string"
      - name: "date"
        type: "timestamp"
      - name: "dateEnd1"
        type: "timestamp"
      - name: "dateEnd2"
        type: "timestamp"
  - name: "bi3"
    description: "bi3"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi3.so"
    params:
      - name: "tagClass"
        type: "string"
      - name: "country"
        type: "string"
  - name: "bi4"
    description: "bi4"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi4.so"
    params:
      - name: "date"
        type: "date"
  - name: "bi5"
    description: "bi5"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi5.so"
    params:
      - name: "tag"
        type: "string"
  - name: "bi6"
    description: "bi6"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi6.so"
    params:
      - name: "tag"
        type: "string"
  - name: "bi7"
    description: "bi7"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi7.so"
    params:
      - name: "tag"
        type: "string"
  - name: "bi8"
    description: "bi8"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi8.so"
    params:
      - name: "tag"
        type: "string"
      - name: "startDate"
        type: "date"
      - name: "endDate"
        type: "date"
  - name: "bi9"
    description: "bi9"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi9.so"
    params:
      - name: "startDate"
        type: "date"
      - name: "endDate"
        type: "date"
  - name: "bi10"
    description: "bi10"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi10.so"
    params:
      - name: "personId"
        type: "long"
      - name: "country"
        type: "string"
      - name: "tagClass"
        type: "string"
      - name: "minPathDistance"
        type: "int"
      - name: "maxPathDistance"
        type: "int"
  - name: "bi11"
    description: "bi11"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi11.so"
    params:
      - name: "country"
        type: "string"
      - name: "startDate"
        type: "date"
      - name: "endDate"
        type: "date"
  - name: "bi12"
    description: "bi12"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi12.so"
    params:
      - name: "startDate"
        type: "date"
      - name: "lengthThreshold"
        type: "int"
      - name: "languages"
        type: "string"
  - name: "bi13"
    description: "bi13"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi13.so"
    params:
      - name: "country"
        type: "string"
      - name: "endDate"
        type: "date"
  - name: "bi14"
    description: "bi14"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi14.so"
    params:
      - name: "country1"
        type: "string"
      - name: "country2"
        type: "string"
  - name: "bi15"
    description: "bi15"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi15.so"
    params:
      - name: "person1Id"
        type: "long"
      - name: "person2Id"
        type: "long"
      - name: "startDate"
        type: "date"
      - name: "endDate"
        type: "date"
  - name: "bi16"
    description: "bi16"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi16.so"
    params:
      - name: "tagA"
        type: "string"
      - name: "dateA"
        type: "date"
      - name: "tagB"
        type: "string"
      - name: "dateB"
        type: "date"
      - name: "maxKnowsLimit"
        type: "int"
  - name: "bi17"
    description: "bi17"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi17.so"
    params:
      - name: "tag"
        type: "string"
      - name: "delta"
        type: "int"
  - name: "bi18"
    description: "bi18"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi18.so"
    params:
      - name: "tag"
        type: "string"
  - name: "bi19"
    description: "bi19"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi19.so"
    params:
      - name: "city1Id"
        type: "long"
      - name: "city2Id"
        type: "long"
  - name: "bi20"
    description: "bi20"
    mode: "READ"
    extension: ".so"
    library: "/path/libbi20.so"
    params:
      - name: "company"
        type: "string"
      - name: "person2Id"
        type: "long"